### ISSUE TITLE
BUG: debug raycasts no longer indicate raycast hits with food objects. Only nematodes

### ISSUE THREAD

**Issue by NicolasWinsten** [Brandon123b/NemaNodes#13]

**Comment by Brandon123b** [comment]
That is because the 2 raycasts overlap and one is drawn on top of the other. We could move both lines slightly to the side so both are visible together. Do you think that would be good?

**Comment by Brandon123b** [comment]
Actually, if the back line is thicker, it might work perfectly to display both? Will test now.

**Comment by NicolasWinsten** [comment]
It's not urgent , but not having accurate debug tools might cause problems.
Since it is for debugging anyway, it might be easiest to somehow decouple drawing the raycast and executing the raycast.  And just draw the rays after the raycasts execute based on their results.

**Comment by Brandon123b** [comment]
That would be possible, but *may* have overhead that I didn't want to implement (Mostly lazy) Would work though.
